webistecs:
  nameOverride: ""
  replicaCount: 1
  image:
    repository: docker.io/niallwootten/webistecs
    tag: 2
  environment:
    aspNetCoreEnvironment: Production
    webistecsContext: "Data Source=/mnt/nfsshare/webistecs-database/webistecs.db"
  imagePullSecret: myregistrykey
  secrets:
    coinbaseApiKeySecret: my-secret
    coinbaseApiSecretSecret: my-secret
  service:
    nodePortHttp: 30080
  volume:
    hostPath: /mnt/nfsshare
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  logging:
    enabled: "true"
    module: "docker"
    fileset:
      stdout: "true"
      stderr: "true"

dbMigrationJob:
  image:
    repository: niallwootten/webistecs-migrations
    tag: 1
  environment:
    aspNetCoreEnvironment: Production
    webistecsContext: "Data Source=/mnt/nfsshare/webistecs-database/webistecs.db"
  volumeMounts:
    - name: db-storage
      mountPath: /mnt/nfsshare/webistecs-database
  volumes:
    - name: db-storage
      persistentVolumeClaim:
        claimName: webistecs-db-pvc
  annotations:
    argocd:
      hook: PreSync
      hookWeight: "5"
      hookDeletePolicy: "BeforeHookCreation,HookSucceeded"
  
nodeExporter:
  name: "node-exporter"
  image: "prom/node-exporter:latest"
  containerPort: 9100