apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webistecs-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-storage
  selector:
    matchLabels:
      type: webistecs-db
