apiVersion: v1
kind: PersistentVolume
metadata:
  name: webistecs-db-pv
  labels:
    type: webistecs-db
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /mnt/nfsshare/webistecs-database
    server: 192.168.1.119