apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.grafanaPVC.name }}
spec:
  selector:
    matchLabels:
      type: grafana
  storageClassName: {{ .Values.grafanaPVC.storageClassName }}
  accessModes:
    - {{ .Values.grafanaPVC.accessModes }}
  resources:
    requests:
      storage: {{ .Values.grafanaPVC.resources.requests.storage }}