apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - name: grafana
      port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.targetPort }}
      nodePort: {{ .Values.grafana.service.nodePort }}
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
