apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
  labels:
    mylabel: prometheus-configmap
data:
  prometheus.yml: |
    global:
      scrape_interval: 1m

    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        metric_relabel_configs:
          
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['192.168.1.119:30088']

      - job_name: 'webistecs'
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_mylabel]
            target_label: webistecs
        static_configs:
          - targets: ['webistecs.default.svc.cluster.local:8000']
          - targets: ['192.168.1.119:30080']

      - job_name: 'node-exporter'
        static_configs:
          - targets: [ '192.168.1.119:9100' ]