apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
      nodePort: 30090
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}
