apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prometheusPVC.name }}
spec:
  selector:
    matchLabels:
      type: prometheus
  storageClassName: {{ .Values.prometheusPVC.storageClassName }}
  accessModes:
    - {{ .Values.prometheusPVC.accessModes }}
  resources:
    requests:
      storage: {{ .Values.prometheusPVC.size }}
