apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.prometheusPV.name }}
  labels:
    type: prometheus
spec:
  capacity:
    storage: {{ .Values.prometheusPV.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.prometheusPV.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.prometheusPV.reclaimPolicy }}
  storageClassName: {{ .Values.prometheusPV.storageClassName }}
  nfs:
    path: {{ .Values.prometheusPV.nfs.path }}
    server: {{ .Values.prometheusPV.nfs.server }}
